### ISSUE TITLE
[BUG] Unable to run manage.py / landingpage not found.

### ISSUE THREAD

**Issue by 0cta** [dfirtrack/dfirtrack#82]
### Issue Description:
Unable to run manage.py after following the installation instructions. The following Django error is supplied when trying to migrate the database or run the supplied tests.

### Environment: 
RHEL8 x64, Python3.6, latest DFIRTrack commit, installed manually (by sticking 1:1 to the installation manual)

### Log output:
(venv) [myuser@mymachine dfirtrack]$ ./manage.py migrate
Traceback (most recent call last):
  File "/local/home/myuser/dfirtrack/venv/lib/python3.6/site-packages/django/apps/config.py", line 244, in create
    app_module = import_module(app_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'landingpage'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/local/home/myuser/dfirtrack/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/local/home/myuser/dfirtrack/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/local/home/myuser/dfirtrack/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/local/home/myuser/dfirtrack/venv/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/local/home/myuser/dfirtrack/venv/lib/python3.6/site-packages/django/apps/config.py", line 250, in create
    app_config_class.__qualname__,
**django.core.exceptions.ImproperlyConfigured: Cannot import 'landingpage'. Check that 'dfirtrack_main.apps.LandingpageConfig.name' is correct.**

Checked for the existence of the LandingPageConfig object containing the name variable in the dfirtrack_main/apps.py, it exists and is world-readable... Any clues? :(

**Comment by stuhli** [comment]
Hi,

I was able to reproduce the error. There seem to be some changes in the newest Django version. Until I find the error, changing `django` to `django==3.1.7` within `requirements.txt` should work.

**Comment by stuhli** [comment]
I recently pushed a fix to `master` branch. Please close this issue if this fixes the error.

**Comment by 0cta** [comment]
Hi Stuhli, thanks for the fix! Works as intended now :)
